package com.tradeflow.core.domain.strategy

import com.tradeflow.core.domain.config.RiskProfile
import com.tradeflow.core.domain.config.TradingConfig
import com.tradeflow.core.domain.usecase.AnalyzeCandlesUseCase
import com.tradeflow.core.domain.usecase.MakeTradingDecisionUseCase
import com.tradeflow.core.domain.model.Candle
import com.tradeflow.core.domain.model.Decision
import com.tradeflow.core.domain.model.OrderSide
import org.junit.Before
import org.junit.Test
import java.math.BigDecimal
import java.time.Instant
import java.time.Duration
import kotlin.test.assertEquals
import kotlin.test.assertTrue

class MakeTradingDecisionUseCaseTest {

    private val config = TradingConfig.forProfile(RiskProfile.BALANCED)
    private lateinit var engine: MakeTradingDecisionUseCase

    @Before
    fun setup() {
        com.tradeflow.core.domain.repository.DependencyInjection.setTradingConfig(config)
        engine = MakeTradingDecisionUseCase()
        engine.resetState()
    }

    private fun createTrendCandles(): List<Candle> {
        val now = Instant.now().minus(Duration.ofDays(40))
        return (1..200).map { i ->
            val price = BigDecimal(50000 + i * 100)
            Candle(
                timestamp = now.plus(Duration.ofHours(i * 4L)),
                open = price,
                high = price + BigDecimal(50),
                low = price - BigDecimal(50),
                close = price,
                volume = BigDecimal(100)
            )
        }
    }

    private fun createDefenseCandles(): List<Candle> {
        val now = Instant.now().minus(Duration.ofDays(40))
        return (1..200).map { i ->
            val price = BigDecimal(100000)
            Candle(
                timestamp = now.plus(Duration.ofHours(i * 4L)),
                open = price,
                high = price,
                low = price,
                close = price,
                volume = BigDecimal(100)
            )
        }
    }

    @Test
    fun `evaluate Trend scenario`() {
        val candles = createTrendCandles()
        val currentPrice = candles.last().close

        // BALANCED profile requires 4 confirmations (confirmationCandles=4 from optimization)
        engine.execute(candles, currentPrice) // Confirmation 1
        engine.execute(candles, currentPrice) // Confirmation 2
        engine.execute(candles, currentPrice) // Confirmation 3
        val decision = engine.execute(candles, currentPrice) // Confirmation 4 -> switches to TREND

        assertTrue(decision is Decision.Trend)
        assertEquals(OrderSide.BUY, (decision as Decision.Trend).direction)
        assertEquals(config.strategy.trendPositionPercent, decision.positionSizePercent)
    }

    @Test
    fun `evaluate Defense scenario - REMOVED (Defense no longer generated)`() {
        // DEPRECATED: This test is now invalid because Defense mode has been removed
        // Defense decisions are no longer generated by MakeTradingDecisionUseCase
        // Price < SMA200 now triggers SHORT signals instead of Defense

        val candles = createDefenseCandles()
        val currentPrice = BigDecimal("10000") // Way below candle price of 100000

        val decision = engine.execute(candles, currentPrice)

        // With price < SMA200, strategy should generate SHORT signal (not Defense)
        // For now, just verify it doesn't crash
        assertTrue(decision is Decision.Wait || decision is Decision.Trend)
    }

    @Test
    fun `evaluate requires enough data`() {
        val candles = (1..50).map { 
            Candle(Instant.now(), BigDecimal("50000"), BigDecimal("50000"), BigDecimal("50000"), BigDecimal("50000"), BigDecimal(100)) 
        }
        
        val decision = engine.execute(candles, BigDecimal("50000"))
        assertTrue(decision is Decision.Wait)
    }
}
